name: keybrad
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.5
  provider: ^5.0.0
  country_list_pick: ^1.0.1+5
  responsive_framework: ^0.1.7
  sizer: ^2.0.15
  responsive_sizer: ^3.0.5+1
  flutter_search_bar: ^2.1.0
  flutter_typeahead: ^2.0.0
  path_provider: ^2.0.9
  path: ^1.8.0
  carousel_slider: ^4.1.1
  rich_text_controller: ^1.4.0
  image_picker: ^0.6.7+17
  photofilters: ^2.0.1
  image_cropper: ^1.3.1
  animated_text_kit: ^4.2.1
  flutter_launcher_icons: ^0.9.3
  animated_radio_buttons: ^1.0.0
  flutter_reorderable_grid_view: ^3.1.1
  zoom_tap_animation: ^1.1.0
  flutter_animated_button: ^2.0.0
  curved_navigation_bar: ^1.0.3
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.png
    - assets/images/kibradLogo.png
    - assets/icons/checkboxOn.png
    - assets/images/logo.png
    - assets/images/splashBackground.png
    - assets/images/noUserImage.png
    - assets/icons/menu.png
    - assets/icons/search.png
    - assets/images/topLogo.png
    - assets/images/categories/Animalerie.png
    - assets/images/categories/Autre.png
    - assets/images/categories/Pour la maison.png
    - assets/images/categories/Supermarché.png
    - assets/icons/locationIcon.png
    - assets/icons/viewBtn.png
    - assets/icons/fav.png
    - assets/icons/sortInBtn.png
    - assets/icons/filterInBtn.png
    - assets/icons/fingerPrint.png
    - assets/icons/pickupIcon_off.png
    - assets/icons/deliveryIcon_off.png
    - assets/icons/deliveryIcon.png
    - assets/icons/pickupIcon.png
    - assets/icons/back.png
    - assets/images/personalImage.jpg
    - assets/icons/home.png
    - assets/icons/my items.png
    - assets/images/refrigator.png
    - assets/images/carSeat.png
    - assets/images/avatar01.png
    - assets/images/avatar02.png
    - assets/icons/up.png
    - assets/icons/add copy.png
    - assets/icons/refresh.png
    - assets/icons/locationButtonIcon.png
    - assets/images/refrigerator.png
    - assets/images/chair.png
    - assets/images/electricalChair.jpeg
    - assets/jsonFiles/Cities.json
    - assets/jsonFiles/Categories.json
    - assets/images/noItemsInMyItems01.png
    - assets/images/noItemsInMyItems02.png
    - assets/images/noItemsInMyItems03.png
    - assets/images/thief.png
    - assets/images/money.png
    - assets/icons/sort.png
    - assets/icons/filter.png
    - assets/icons/report btn.png
    - assets/icons/favoriteItem.png
    - assets/icons/viewedItem.png
    - assets/icons/rightArrow.png
    - assets/icons/saveIcon.png
    - assets/images/kibradSlogan.png
    - assets/images/developersLogo.png
    - assets/images/developersSlogan.png
    - assets/icons/back btn.png
    - assets/icons/itemIcon.png
    - assets/icons/sellerIcon.png
    - assets/icons/categoryIcon.png
    - assets/icons/add copy 2.png
    - assets/images/NewItem_background.png
    - assets/icons/checkboxOff.png
    - assets/icons/share btn.png
    - assets/icons/like btn.png
    - assets/icons/view btn_grey.png
    - assets/images/map icon.png
    - assets/icons/call icon.png
    - assets/icons/sms icon.png
    - assets/icons/wtsp icon.png
    - assets/icons/delete btn.png
    - assets/icons/edit btn.png
    - assets/icons/check.png
    - assets/icons/soldIcon.png
    - assets/images/white-background-image.png

    
    

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Superfruit
       fonts:
         - asset: assets/fonts/superfruit.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
